# dbt_project.yml
name: my_new_project
version: "1.0.0"
config-version: 2
profile: default
 
models:
  my_new_project:
    +schema: consumption     # default schema under the connected DB
    stage:
      +schema: consumption
      # +materialized: view
    integration_staging:
      +schema: integration_staging