{{ config(materialized="incremental", unique_key="INTEGRATION_ID") }}

with gl_ledgers as (
    select * 
    from {{
           ref(
                "gl_ledger"
           ) 
    }})    , 
    ct_gl_ledgers_d_stg as (

SELECT 
  GLLEDGERS_FILTER_A.LEDGER_ID AS LEDGER_ID, 
  GLLEDGERS_FILTER_A.CHART_OF_ACCOUNTS_ID AS COA_ID, 
  GLLEDGERS_FILTER_A.NAME AS LEDGER_NAME, 
  GLLEDGERS_FILTER_A.SHORT_NAME AS LEDGER_SHORT_NAME, 
  GLLEDGERS_FILTER_A.DESCRIPTION AS DESCRIPTION, 
  GLLEDGERS_FILTER_A.LEDGER_CATEGORY_CODE AS LEDGER_CATEGORY_CODE, 
  CASE 
    WHEN GLLEDGERS_FILTER_A.OBJECT_TYPE_CODE = 'L' THEN 'Ledger' 
    WHEN GLLEDGERS_FILTER_A.OBJECT_TYPE_CODE = 'S' THEN 'Ledger Set' 
    ELSE GLLEDGERS_FILTER_A.OBJECT_TYPE_CODE 
  END AS LEDGER_TYPE, 
  GLLEDGERS_FILTER_A.CURRENCY_CODE AS LEDGER_CURR_CODE, 
  GLLEDGERS_FILTER_A.CREATION_DATE AS CREATION_DT, 
  GLLEDGERS_FILTER_A.LAST_UPDATE_DATE AS LAST_UPDATE_DT, 
  GLLEDGERS_FILTER_A.CREATED_BY AS CREATED_BY, 
  GLLEDGERS_FILTER_A.LAST_UPDATED_BY AS LAST_UPDATED_BY, 
  CAST(GLLEDGERS_FILTER_A.LEDGER_ID AS VARCHAR) AS INTEGRATION_ID, 
  1000 AS DATASOURCE_NUM_ID, 
  GLLEDGERS_FILTER_A.LEDGER_CATEGORY_CODE AS LEDGER_CAT_CODE 
FROM 
  GL_LEDGERS GLLEDGERS_FILTER_A
  
    )

select * from ct_gl_ledgers_d_stg